version: "2"

services:
    web:
        build: .
        restart: always
        ports:
            - "127.0.0.1:8090:3000"
        depends_on:
            - mongo
    mongo:
        restart: always
        image: mongo
